version: "3.8"
services:
  api:
    build: ./server
    container_name: api-server
    ports:
      - 4000:4000
  web: 
    build: ./client
    container_name: web-server
    ports:
      - 8000:8000
