# v1 refers to the core API group, which includes resources like Pods, Services, ConfigMaps, etc.
# apps/v1 is used for higher-level abstractions like Deployments and StatefulSets.
# batch/v1 is used for CronJobs.
# networking.k8s.io/v1 is used for Ingress resources.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ajmalj/umsclient:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080